### ISSUE TITLE
error about get_FC

### ISSUE THREAD

**Issue by rick-lzr** [AI-secure/SemAttack#7]
~~~
Traceback (most recent call last):
  File "get_FC.py", line 103, in <module>
    embedding_space = torch.load(args.embedding_data)
  File "/share/home/x/.conda/envs/l/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/share/home/x/.conda/envs/l/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/share/home/x/.conda/envs/l/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 's.pt'
~~~
找不到s.pt。请问这里使用["Visualizing and Measuring the Geometry of BERT"](https://arxiv.org/abs/1906.02715)是如何使用的？在github上的代码运行完成后是一个json文件，没有pt文件。pt文件最后生成的数据究竟是什么样子的呢？请问可以公开s.pt吗？

**Comment by rick-lzr** [comment]
s.pt是您写在English\bert\util.py中的文件
~~~
parser.add_argument('--embedding-data', type=str, default='s.pt',
                        help='location of the embedding data, should be a json file')
~~~
是embedding-data，但是仍不清楚是如何计算的，请问可以帮我看看吗？还是说您已公布如何计算，只是我没有看到这部分内容。

**Comment by garyxcj** [comment]
我们提供了基于 wiki data 计算的 embedding space，请参见 [https://drive.google.com/file/d/1KsSy3NHA5bTG2Iseq2D_ULKeckg_I9r5/view?usp=sharing](https://drive.google.com/file/d/1KsSy3NHA5bTG2Iseq2D_ULKeckg_I9r5/view?usp=sharing)
